### PR TITLE
Update redux dependencies

### PR DESCRIPTION
**Pull request by zeroimpl**
This updates the redux dependencies per https://github.com/mattermost/mattermost-redux/pull/699

See https://github.com/mattermost/mattermost-server/pull/9780 for more information.

#### Ticket Link
[GH-9755](https://github.com/mattermost/mattermost-server/issues/9755)

### CODE REVIEW

**Comment by wiersgallak** [comment]
Thanks @zeroimpl Couple of things I am noted in my testing. 

1.  Search bar is shown for admins, but not for members.  
search bar available admin
search bar missing for user-1

2.  Under Account Settings > View Members > Team >Manage members- just shows a loading screen when the "@" precedes the search characters
team manage members loading screen

3.  When you are doing a search using the FROM: modifier, when the "@" precedes the search characters, no results are returned
from including the at

4. When searching for an email and using a "@" preceding the search, results matching the characters are returned even though their is not an "@" sign preceding the characters in the result set.  From reviewing your logic, this seems to be expected as I believe the "@" is just being ignored, but from a user perspective this could look like a bug as you can see that it is not a direct match to the results returned. 
user-6 before at returns

**Comment by zeroimpl** [comment]
Thanks for the review @wiersgallak!

1) I feel likely that's unrelated to my change as I only modified the filtering logic. Could you confirm if other instances are behaving properly for that? A similar issue had been reported on my initial PR https://github.com/mattermost/mattermost-server/pull/9780, but was later confirmed to happen on other instances as well. 

2) It looks like this happens when anything is typed into that field, not just ones starting with "@". A javascript error is logged: "Unhandled Promise Rejection: TypeError: t.props.actions.loadStatusesForProfilesList is not a function" - It seems like this could be a regression in #1951 as it is coming from this line: https://github.com/mattermost/mattermost-webapp/blame/a714e5d1d45f9c417ff401a187cb4feab947c1d1/components/add_users_to_team/add_users_to_team.jsx#L70

3) You're right - my change didn't add support for searches like "from: @name". It feels like that's not as important, but I agree would be nice to support.

4) Yeah that's how it's implemented at the moment. I could look at making it so that @ doesn't match against the start of the email if you like.

**Comment by zeroimpl** [comment]
Looks like 3. would be a server backend fix. It's in the code for searching posts, as opposed to searching by users. I think it'd make sense to address that in a follow-up PR.

**Comment by zeroimpl** [comment]
@wiersgallak: I've pushed a fix for issue 4.

**Comment by wiersgallak** [comment]
Thank you for your adjustments @zeroimpl.  

1.  Once the issue has been identified and fixed, we may want to rebased your PR so that all functionality works as expected. 

2.  I am going to ask @jwilander to assist as he worked on that PR you referenced and may be able to assist us on that issue.  

3.  Since it is different codebase and the usernames are not formatted the same with the preceding "@" I agree, we can address in a later PR.  

4.  Tested and it looks good.  Thank you so much for addressing 👍

**Comment by jwilander** [comment]
2. If it reproduces on master then we should file a bug and triage it appropriately. No need to fix it in this PR if it wasn't broken here

**Comment by wiersgallak** [comment]
Thanks.  I have notified our QA team about this PR and they will be reviewing a little later this week.

**Comment by jasonblais** [comment]
@zeroimpl I generated a new test server - looks like this is queued for QA review next. Big thanks for your help with this contribution!

**Comment by hanzei** [comment]
@zeroimpl Could you please rebase the PR? Let me know, if you need help with with.

@jasonblais @wiersgallak What is the status on the QA review?

**Comment by wiersgallak** [comment]
Thanks for following up @hanzei.  I reminded QA last week this was still pending their review.  We will make sure this is reviewed in the next couple days.  Sorry for the delay @zeroimpl.

**Comment by lindalumitchell** [comment]
@zeroimpl @wiersgallak all my apologies for the delay on QA review for this one, due to an unfortunate combination of holiday schedules followed by compressed release schedule. Now I'm afraid it looks like there are conflicts here and the spinmint won't build (the last one was auto-destroyed after the time limit, so I'm trying to build a new one). Not sure who would be best to take a look to help resolve?

**Comment by zeroimpl** [comment]
Thanks team. @lindalumitchell I've gone ahead and rebased this, which hopefully should let you redo the spinmint.

**Comment by lindalumitchell** [comment]
@zeroimpl this is looking great! Just one thing so far: I do still see the issue others mentioned with the search bar missing for non-system-admin user. I'm unable to reproduce it on master.

@esethna you mentioned in https://github.com/mattermost/mattermost-server/pull/9780, where this issue was also described, that you were able to repro the missing search bar on another server. Do you recall where else you saw it?

**Comment by cpanato** [comment]
`Setup Test Server` label detected. Spinmint test server created if build succeeds (checks pass and no conflicts with base branch).

**Comment by cpanato** [comment]
Spintmint test server creation failed. See the logs for more information.

**Comment by lindalumitchell** [comment]
@zeroimpl if you log in as a non-system-admin user, do you reproduce the issue of the missing search bar? I see this when logged in as a non-admin:

Missing on spinmint:
spinmint-search-bar-missing
 
Present on master (community-daily):
master-search-bar-present

Notes:
- System admin does see the search bar
- If the screen is narrowed to go into table/mobile mode, the search icon does appear, and can be clicked to open the search bar. It just reproduces in wide enough view to accommodate the search bar

**Comment by zeroimpl** [comment]
Hmm, when I login to that spinmint as either user, I see the search bar.

screen shot 2019-01-10 at 11 07 12 pm

Is the problem in your case have to do with the the size of the browser window? I see that if I make the browser window a bit narrower, the search bar disappears.

**Comment by lindalumitchell** [comment]
So strange; when I look now, I do indeed see the search bar for user-1. But before, when the browser was narrow I saw the search icon as expected, but when I made it wider, there was no search bar (nor icon). The screenshots I attached were both wide browsers, and sysadmin saw the search bar but user-1 did not. Hm. 

Well I guess it's not reproducing anymore for me either. I'll keep an eye out for it on other servers. Maybe there's another issue going on somehow that has nothing to do with this spinmint.

And in that case, this looks good to me! 👍

**Comment by zeroimpl** [comment]
Great thanks. Let me know if you need anything else for these

**Comment by grundleborg** [comment]
OK, looks like this and the redux PR is all in order now. Next steps:
1. Merge the redux PR
2. Update the commit hash in the webapp (via this PR) to the *merged* redux commit, and then merge this one.
