### PR TITLE
MM-26322 Update mattermost-redux to make reorganizing sidebar optimistic

### PR DESCRIPTION
**Pull request by hmhealey**
Using https://github.com/mattermost/mattermost-redux/pull/1187 in the webapp

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-26322

#### Related Pull Requests
https://github.com/mattermost/mattermost-redux/pull/1187

### CODE REVIEW

**Comment by hmhealey** [comment]
Tests are failing because this is missing the changes from https://github.com/mattermost/mattermost-webapp/pull/5917

**Comment by devinbinnie** [comment]
You have a type error:
```
components/sidebar/sidebar_channel/sidebar_channel_menu/index.ts:17:25 - error TS2305: Module '"../../../../node_modules/mattermost-redux/utils/channel_utils"' has no exported member 'isFavoriteChannel'.

17 import {isChannelMuted, isFavoriteChannel} from 'mattermost-redux/utils/channel_utils';
```

Did we remove/rename that function?

**Comment by hmhealey** [comment]
Yep, that's fixed in https://github.com/mattermost/mattermost-webapp/pull/5917

**Comment by hmhealey** [comment]
Holding off on QA review for now since the test server is unusable without that other PR.

**Comment by hmhealey** [comment]
When cherry-picked onto the release branch, the mattermost-redux commit must be updated to `9831ef3e2381839151a0b1a22cbc5585f5c58436`

**Comment by prapti** [comment]
@hmhealey Testing mostly went well, but I noticed two things:

1. DMs and GMs cannot be reorganized within the Direct Messages category. Is this by design?
2. Channels can't get dropped to the bottom of a newly created category, however dropping them at the top or the middle of a new category and dragging/dropping them to the bottom of Favorites and Channels work fine. Is this something that can be fixed in this PR as well?

**Comment by hmhealey** [comment]
> 1. DMs and GMs cannot be reorganized within the Direct Messages category. Is this by design?

Yeah, that's by design. The Direct Messages category has the channels automatically ordered

> 2. Channels can't get dropped to the bottom of a newly created category, however dropping them at the top or the middle of a new category and dragging/dropping them to the bottom of Favorites and Channels work fine. Is this something that can be fixed in this PR as well?

I think there's an outstanding ticket for the drop zones being a bit off for new categories. We'll have to address that later since I don't think it's going to make it in for 5.26 at this point.

**Comment by hmhealey** [comment]
The changes to mattermost-redux were included on master in https://github.com/mattermost/mattermost-webapp/pull/5447. I'll submit a new PR to the release branch to include those.
